In [114]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

In [115]:
train = np.loadtxt("train.csv", delimiter=",",dtype="str")
test = np.loadtxt("test.csv", delimiter=",",dtype="str")

In [116]:
train

array([['label', 'pixel0', 'pixel1', ..., 'pixel781', 'pixel782',
        'pixel783'],
       ['1', '0', '0', ..., '0', '0', '0'],
       ['0', '0', '0', ..., '0', '0', '0'],
       ...,
       ['7', '0', '0', ..., '0', '0', '0'],
       ['6', '0', '0', ..., '0', '0', '0'],
       ['9', '0', '0', ..., '0', '0', '0']], dtype='<U8')

In [184]:
train_1 = train[1:,:]
test_1 = test[1:,:]
np.random.shuffle(train_1)
train_1 = train_1[:,1:].astype("float64")
labels_1 = train_1[:,0].astype("float64")
test_1 = test_1.astype("float64")

train_1

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [181]:
train_2 = train_1.reshape(train_size)
test_2 = test_1.reshape(test_size)
labels_2 = labels_1.copy()

In [182]:
labels_2

array([0., 0., 0., ..., 0., 0., 0.])

In [89]:
arr = np.arange(1, 11)
np.random.shuffle(arr)
print(arr)

[10  4  1  9  7  3  2  5  6  8]


array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [67]:
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:

size = train_1.shape[1]

train_size = tuple([train_1.shape[0],int(np.sqrt(size)),int(np.sqrt(size)),1])
test_size = tuple([test_1.shape[0],int(np.sqrt(size)),int(np.sqrt(size)),1])

train = np.reshape(train_1,train_size)
test = np.reshape(test_1,test_size)


NameError: name 'train_1' is not defined

In [30]:
model = tf.keras.models.Sequential([
    
    tf.keras.layers.Resizing(height=64,width=64),
    tf.keras.layers.Conv2D(8,3,activation="relu",input_shape=(64,64,1)),
    tf.keras.layers.MaxPooling2D(pool_size=(2,2)),
    tf.keras.layers.Conv2D(16,3,activation="relu"),
    tf.keras.layers.MaxPooling2D(pool_size=(2,2)),
    tf.keras.layers.Conv2D(32,3,activation="relu"),
    tf.keras.layers.MaxPooling2D(pool_size=(2,2)),
    tf.keras.layers.Conv2D(64,3,activation="relu"),
    tf.keras.layers.MaxPooling2D(pool_size=(2,2)),

    tf.keras.layers.Flatten(),

    tf.keras.layers.Dense(32,activation="relu"),
    tf.keras.layers.Dense(units=np.unique(labels).shape[0],activation="softmax")

])

In [ ]:
model.compile(optimizer=tf.keras.optimizers.RMSprop(),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=tf.keras.metrics.mean_squared_error,
              batch_size=32,
              epochs=100,
              verbose=1,
              shuffle=True,
              )