## Deep Learning

Now, we are done with both exploratory data analysis and preprocessing. Now we will go ahead with performing machine learning.

In [72]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

In [73]:
df_train_X_1 = np.load("X_train_1.npz")
df_train_X_2 = np.load("X_train_2.npz")
df_train_X_3 = np.load("X_train_3.npz")
df_train_X_4 = np.load("X_train_4.npz")

In [74]:
df_train_y_1 = np.load("y_train_1.npz")
df_train_y_2 = np.load("y_train_2.npz")
df_train_y_3 = np.load("y_train_3.npz")
df_train_y_4 = np.load("y_train_4.npz")

In [75]:
df_test_X = np.load("X_test.npz")

### Checking the training and testing datasets

In [76]:
X_train_1 = df_train_X_1["arr_0"]
X_train_1

array([[2.0130e+03, 1.0000e+00, 1.0000e+00, ..., 0.0000e+00, 9.3366e+01,
        1.0000e+00],
       [2.0130e+03, 1.0000e+00, 1.0000e+00, ..., 0.0000e+00, 9.3366e+01,
        1.0000e+00],
       [2.0130e+03, 1.0000e+00, 1.0000e+00, ..., 0.0000e+00, 9.3366e+01,
        1.0000e+00],
       ...,
       [2.0130e+03, 5.0000e+00, 2.8000e+01, ..., 0.0000e+00, 9.4650e+01,
        0.0000e+00],
       [2.0130e+03, 5.0000e+00, 2.8000e+01, ..., 0.0000e+00, 9.4650e+01,
        0.0000e+00],
       [2.0130e+03, 5.0000e+00, 2.8000e+01, ..., 0.0000e+00, 9.4650e+01,
        0.0000e+00]])

In [44]:
X_train_2 = df_train_X_2["arr_0"]
X_train_2

array([[2013.  ,    5.  ,   28.  , ...,    0.  ,   94.65,    0.  ],
       [2013.  ,    5.  ,   28.  , ...,    0.  ,   94.65,    0.  ],
       [2013.  ,    5.  ,   28.  , ...,    0.  ,   94.65,    0.  ],
       ...,
       [2013.  ,   10.  ,   22.  , ...,    0.  ,   97.63,    0.  ],
       [2013.  ,   10.  ,   22.  , ...,    0.  ,   97.63,    0.  ],
       [2013.  ,   10.  ,   22.  , ...,    0.  ,   97.63,    0.  ]])

In [45]:
X_train_3 = df_train_X_3["arr_0"]
X_train_3

array([[2013.  ,   10.  ,   22.  , ...,    0.  ,   97.63,    0.  ],
       [2013.  ,   10.  ,   22.  , ...,    0.  ,   97.63,    0.  ],
       [2013.  ,   10.  ,   22.  , ...,    0.  ,   97.63,    0.  ],
       ...,
       [2014.  ,    3.  ,   19.  , ...,    0.  ,  100.71,    0.  ],
       [2014.  ,    3.  ,   19.  , ...,    0.  ,  100.71,    0.  ],
       [2014.  ,    3.  ,   19.  , ...,    0.  ,  100.71,    0.  ]])

In [46]:
X_train_4 = df_train_X_4["arr_0"]
X_train_4

array([[2.0140e+03, 3.0000e+00, 1.9000e+01, ..., 0.0000e+00, 1.0071e+02,
        0.0000e+00],
       [2.0140e+03, 3.0000e+00, 1.9000e+01, ..., 0.0000e+00, 1.0071e+02,
        0.0000e+00],
       [2.0140e+03, 3.0000e+00, 1.9000e+01, ..., 0.0000e+00, 1.0071e+02,
        0.0000e+00],
       ...,
       [2.0140e+03, 8.0000e+00, 1.3000e+01, ..., 1.0000e+00, 9.7570e+01,
        0.0000e+00],
       [2.0140e+03, 8.0000e+00, 1.3000e+01, ..., 1.0000e+00, 9.7570e+01,
        0.0000e+00],
       [2.0140e+03, 8.0000e+00, 1.3000e+01, ..., 1.0000e+00, 9.7570e+01,
        0.0000e+00]])

In [68]:
X_train = np.row_stack([X_train_1,X_train_2,X_train_3,X_train_4])

In [71]:
X_test = df_test_X["arr_0"]
X_test

array([[ 0.        ,  0.        , -1.62697843, ..., -0.96362411,
        -0.6790212 , -0.25819889],
       [ 0.        ,  0.        , -1.62697843, ..., -0.96362411,
        -0.6790212 , -0.25819889],
       [ 0.        ,  0.        , -1.62697843, ..., -0.96362411,
        -0.6790212 , -0.25819889],
       ...,
       [ 0.        ,  0.        ,  1.62697843, ...,  1.03774904,
         0.02552711, -0.25819889],
       [ 0.        ,  0.        ,  1.62697843, ...,  1.03774904,
         0.02552711, -0.25819889],
       [ 0.        ,  0.        ,  1.62697843, ...,  1.03774904,
         0.02552711, -0.25819889]])

In [70]:
y_train_2 = df_train_y_2["arr_0"]
y_train_2

array([[310.173],
       [227.   ],
       [  0.   ],
       ...,
       [ 22.   ],
       [  0.   ],
       [  0.   ]])