## Deep Learning

Now, we are done with both exploratory data analysis and preprocessing. Now we will go ahead with performing machine learning.

In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

In [16]:
df_train_X_1 = np.load("X_train_1.npz")
df_train_X_2 = np.load("X_train_2.npz")
df_train_X_3 = np.load("X_train_3.npz")
df_train_X_4 = np.load("X_train_4.npz")

In [17]:
df_train_y_1 = np.load("y_train_1.npz")
df_train_y_2 = np.load("y_train_2.npz")
df_train_y_3 = np.load("y_train_3.npz")
df_train_y_4 = np.load("y_train_4.npz")

In [18]:
df_test_X = np.load("X_test.npz")

### Combining the training and testing datasets

In [19]:
X_train_1 = df_train_X_1["arr_0"]
X_train_2 = df_train_X_2["arr_0"]
X_train_3 = df_train_X_3["arr_0"]
X_train_4 = df_train_X_4["arr_0"]

y_train_1 = df_train_y_1["arr_0"]
y_train_2 = df_train_y_2["arr_0"]
y_train_3 = df_train_y_3["arr_0"]
y_train_4 = df_train_y_4["arr_0"]

X_test = df_test_X["arr_0"]

In [28]:
X_train_1 = np.row_stack([X_train_1,X_train_2,X_train_3,X_train_4])
y_train_1 = np.row_stack([y_train_1,y_train_2,y_train_3,y_train_4])

In [29]:
X_train = X_train_1[0:int(3*len(X_train_1)/4),:]
X_valid = X_train_1[int(3*len(X_train_1)/4):,:]

y_train = y_train_1[0:int(3*len(y_train_1)/4),:]
y_valid = y_train_1[int(3*len(y_train_1)/4):,:]

In [30]:
X_train

array([[2.0130e+03, 1.0000e+00, 1.0000e+00, ..., 0.0000e+00, 9.3366e+01,
        1.0000e+00],
       [2.0130e+03, 1.0000e+00, 1.0000e+00, ..., 0.0000e+00, 9.3366e+01,
        1.0000e+00],
       [2.0130e+03, 1.0000e+00, 1.0000e+00, ..., 0.0000e+00, 9.3366e+01,
        1.0000e+00],
       ...,
       [2.0140e+03, 3.0000e+00, 1.9000e+01, ..., 0.0000e+00, 1.0071e+02,
        0.0000e+00],
       [2.0140e+03, 3.0000e+00, 1.9000e+01, ..., 0.0000e+00, 1.0071e+02,
        0.0000e+00],
       [2.0140e+03, 3.0000e+00, 1.9000e+01, ..., 0.0000e+00, 1.0071e+02,
        0.0000e+00]])

In [31]:
X_valid

array([[2.0140e+03, 3.0000e+00, 1.9000e+01, ..., 0.0000e+00, 1.0071e+02,
        0.0000e+00],
       [2.0140e+03, 3.0000e+00, 1.9000e+01, ..., 0.0000e+00, 1.0071e+02,
        0.0000e+00],
       [2.0140e+03, 3.0000e+00, 1.9000e+01, ..., 0.0000e+00, 1.0071e+02,
        0.0000e+00],
       ...,
       [2.0140e+03, 8.0000e+00, 1.3000e+01, ..., 1.0000e+00, 9.7570e+01,
        0.0000e+00],
       [2.0140e+03, 8.0000e+00, 1.3000e+01, ..., 1.0000e+00, 9.7570e+01,
        0.0000e+00],
       [2.0140e+03, 8.0000e+00, 1.3000e+01, ..., 1.0000e+00, 9.7570e+01,
        0.0000e+00]])

In [32]:
y_train

array([[  0.   ],
       [  0.   ],
       [  0.   ],
       ...,
       [250.863],
       [  8.   ],
       [485.   ]])

In [33]:
y_valid

array([[588.   ],
       [116.357],
       [119.   ],
       ...,
       [ 10.   ],
       [  0.   ],
       [ 69.116]])

In [34]:
X_valid

array([[2.0140e+03, 3.0000e+00, 1.9000e+01, ..., 0.0000e+00, 1.0071e+02,
        0.0000e+00],
       [2.0140e+03, 3.0000e+00, 1.9000e+01, ..., 0.0000e+00, 1.0071e+02,
        0.0000e+00],
       [2.0140e+03, 3.0000e+00, 1.9000e+01, ..., 0.0000e+00, 1.0071e+02,
        0.0000e+00],
       ...,
       [2.0140e+03, 8.0000e+00, 1.3000e+01, ..., 1.0000e+00, 9.7570e+01,
        0.0000e+00],
       [2.0140e+03, 8.0000e+00, 1.3000e+01, ..., 1.0000e+00, 9.7570e+01,
        0.0000e+00],
       [2.0140e+03, 8.0000e+00, 1.3000e+01, ..., 1.0000e+00, 9.7570e+01,
        0.0000e+00]])

In [36]:
print("Number of rows in training dataset   : ",len(X_train))
print("Number of rows in validation dataset : ",len(X_valid))
print("Number of rows in testing dataset    : ",len(X_test))

Number of rows in training dataset   :  786431
Number of rows in validation dataset :  262144
Number of rows in testing dataset    :  28512


In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=32,activation="relu"),
    tf.keras.layers.Dense(units=64,activation="relu"),
    tf.keras.layers.Dense(units=128,activation="relu"),
    tf.keras.layers.Dense(units=1)
])

In [ ]:
optimizer = tf.keras.optimizers.legacy.RMSprop(learning_rate=0.001)
model.compile(optimizer="adam",loss="mean_squared_error",metrics=["accuracy"])
model.fit(x=X_train,y=y_train,epochs=10,validation_data=(X_valid,y_valid),callbacks=tf.keras.callbacks.EarlyStopping())