## Deep Learning

Now, we are done with both exploratory data analysis and preprocessing. Now we will go ahead with performing machine learning.

In [27]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

In [28]:
df_train_X_1 = np.load("X_train_1.npz")
df_train_X_2 = np.load("X_train_2.npz")
df_train_X_3 = np.load("X_train_3.npz")
df_train_X_4 = np.load("X_train_4.npz")

In [29]:
df_train_y_1 = np.load("y_train_1.npz")
df_train_y_2 = np.load("y_train_2.npz")
df_train_y_3 = np.load("y_train_3.npz")
df_train_y_4 = np.load("y_train_4.npz")

In [30]:
df_test_X = np.load("X_test.npz")

### Combining the training and testing datasets

In [31]:
X_train_1 = df_train_X_1["arr_0"]
X_train_2 = df_train_X_2["arr_0"]
X_train_3 = df_train_X_3["arr_0"]
X_train_4 = df_train_X_4["arr_0"]

y_train_1 = df_train_y_1["arr_0"]
y_train_2 = df_train_y_2["arr_0"]
y_train_3 = df_train_y_3["arr_0"]
y_train_4 = df_train_y_4["arr_0"]

X_test = df_test_X["arr_0"]

In [20]:
X_train = np.row_stack([X_train_1,X_train_2,X_train_3,X_train_4])
y_train = np.row_stack([y_train_1,y_train_2,y_train_3,y_train_4])

In [21]:
X_train

array([[2.0130e+03, 1.0000e+00, 1.0000e+00, ..., 0.0000e+00, 9.3366e+01,
        1.0000e+00],
       [2.0130e+03, 1.0000e+00, 1.0000e+00, ..., 0.0000e+00, 9.3366e+01,
        1.0000e+00],
       [2.0130e+03, 1.0000e+00, 1.0000e+00, ..., 0.0000e+00, 9.3366e+01,
        1.0000e+00],
       ...,
       [2.0140e+03, 8.0000e+00, 1.3000e+01, ..., 1.0000e+00, 9.7570e+01,
        0.0000e+00],
       [2.0140e+03, 8.0000e+00, 1.3000e+01, ..., 1.0000e+00, 9.7570e+01,
        0.0000e+00],
       [2.0140e+03, 8.0000e+00, 1.3000e+01, ..., 1.0000e+00, 9.7570e+01,
        0.0000e+00]])

In [22]:
y_train

array([[ 0.   ],
       [ 0.   ],
       [ 0.   ],
       ...,
       [10.   ],
       [ 0.   ],
       [69.116]])

In [23]:
X_test

array([[2.017e+03, 8.000e+00, 1.600e+01, ..., 0.000e+00, 4.680e+01,
        0.000e+00],
       [2.017e+03, 8.000e+00, 1.600e+01, ..., 0.000e+00, 4.680e+01,
        0.000e+00],
       [2.017e+03, 8.000e+00, 1.600e+01, ..., 0.000e+00, 4.680e+01,
        0.000e+00],
       ...,
       [2.017e+03, 8.000e+00, 3.100e+01, ..., 1.000e+00, 4.726e+01,
        0.000e+00],
       [2.017e+03, 8.000e+00, 3.100e+01, ..., 1.000e+00, 4.726e+01,
        0.000e+00],
       [2.017e+03, 8.000e+00, 3.100e+01, ..., 1.000e+00, 4.726e+01,
        0.000e+00]])

In [24]:
print("Number of rows in training dataset : ",len(X_train))
print("Number of rows in testing dataset  : ",len(X_test))

Number of rows in training dataset :  1048575
Number of rows in testing dataset  :  28512


In [25]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=64,activation="relu"),
    tf.keras.layers.Dense(units=256,activation="relu"),
    tf.keras.layers.Dense(units=512,activation="relu"),
    tf.keras.layers.Dense(units=1,activation='softmax')
])

In [ ]:
model.compile(optimizer="adam",loss='binary_crossentropy',metrics=["binary_accuracy"])
model.fit(X_train,y_train,epochs=5,batch_size=1)