## Machine Learning

Now, we are done with both exploratory data analysis and preprocessing. Now we will go ahead with performing machine learning.

### Importing all packages

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import *
from sklearn.linear_model import *
from math import *
from sklearn.ensemble import *
from sklearn.feature_selection import *
from sklearn.feature_extraction import *
from sklearn.naive_bayes import *
from sklearn.discriminant_analysis import *
from sklearn.preprocessing import *
from sklearn.metrics import *
from sklearn.neighbors import *
from sklearn.cluster import *

In [42]:
df_x = pd.read_csv("train_X_preprocessed.csv")
df_y = pd.read_csv("train_y_preprocessed.csv")
df_test = pd.read_csv("test_preprocessed.csv")

In [43]:
X_train.head()

date_year  date_month  date_day  store_nbr_0  store_nbr_1  store_nbr_2  \
0       2013           1         1            0            0            0   
1       2013           1         1            0            0            0   
2       2013           1         1            0            0            0   
3       2013           1         1            0            0            0   
4       2013           1         1            0            0            0   

   store_nbr_3  store_nbr_4  store_nbr_5  family_0  ...  type_0  type_1  \
0            0            0            0         0  ...       0       1   
1            0            0            0         0  ...       0       1   
2            0            0            0         0  ...       0       1   
3            0            0            0         0  ...       0       1   
4            0            0            0         0  ...       0       1   

   type_2  cluster_0  cluster_1  cluster_2  cluster_3  cluster_4  dcoilwtico  \
0       1          0          1          1          0          0      93.366   
1       1          0          1          1          0          0      93.366   
2       1          0          1          1          0          0      93.366   
3       1          0          1          1          0          0      93.366   
4       1          0          1          1          0          0      93.366   

   holiday?  
0       1.0  
1       1.0  
2       1.0  
3       1.0  
4       1.0  

[5 rows x 35 columns]

In [44]:
y_train.head()

sales
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0

In [45]:
X_test.head()

date_year  date_month  date_day  store_nbr_0  store_nbr_1  store_nbr_2  \
0       2017           8        16            0            0            0   
1       2017           8        16            0            0            0   
2       2017           8        16            0            0            0   
3       2017           8        16            0            0            0   
4       2017           8        16            0            0            0   

   store_nbr_3  store_nbr_4  store_nbr_5  family_0  ...  type_0  type_1  \
0            0            0            0         0  ...       0       1   
1            0            0            0         0  ...       0       1   
2            0            0            0         0  ...       0       1   
3            0            0            0         0  ...       0       1   
4            0            0            0         0  ...       0       1   

   type_2  cluster_0  cluster_1  cluster_2  cluster_3  cluster_4  dcoilwtico  \
0       1          0          1          1          0          0        46.8   
1       1          0          1          1          0          0        46.8   
2       1          0          1          1          0          0        46.8   
3       1          0          1          1          0          0        46.8   
4       1          0          1          1          0          0        46.8   

   holiday?  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  

[5 rows x 35 columns]

In [46]:
print("Number of rows in X_train : ",len(X_train))
print("Number of rows in y_train : ",len(y_train))
print("Number of rows in X_test  : ",len(X_test))

Number of rows in X_train :  1048575
Number of rows in y_train :  1048575
Number of rows in X_test  :  28512


In [47]:
X_train.dtypes

date_year        int64
date_month       int64
date_day         int64
store_nbr_0      int64
store_nbr_1      int64
store_nbr_2      int64
store_nbr_3      int64
store_nbr_4      int64
store_nbr_5      int64
family_0         int64
family_1         int64
family_2         int64
family_3         int64
family_4         int64
family_5         int64
onpromotion      int64
city_0           int64
city_1           int64
city_2           int64
city_3           int64
city_4           int64
state_0          int64
state_1          int64
state_2          int64
state_3          int64
type_0           int64
type_1           int64
type_2           int64
cluster_0        int64
cluster_1        int64
cluster_2        int64
cluster_3        int64
cluster_4        int64
dcoilwtico     float64
holiday?       float64
dtype: object

In [48]:
X_test.dtypes

date_year        int64
date_month       int64
date_day         int64
store_nbr_0      int64
store_nbr_1      int64
store_nbr_2      int64
store_nbr_3      int64
store_nbr_4      int64
store_nbr_5      int64
family_0         int64
family_1         int64
family_2         int64
family_3         int64
family_4         int64
family_5         int64
onpromotion      int64
city_0           int64
city_1           int64
city_2           int64
city_3           int64
city_4           int64
state_0          int64
state_1          int64
state_2          int64
state_3          int64
type_0           int64
type_1           int64
type_2           int64
cluster_0        int64
cluster_1        int64
cluster_2        int64
cluster_3        int64
cluster_4        int64
dcoilwtico     float64
holiday?       float64
dtype: object

In [49]:
y_train.dtypes

sales    float64
dtype: object

In [50]:
sgd = SGDClassifier()
model = sgd.fit(X_train,y_train)
y_pred = model.predict(X_test)

/Users/amith/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


ValueError: Unknown label type: (array([0.0000e+00, 1.2200e-01, 1.4600e-01, ..., 2.2534e+04, 2.6067e+04,
       4.6271e+04]),)

In [53]:
y_train_1 = y_train.to_numpy()
y_train_1

array([[ 0.   ],
       [ 0.   ],
       [ 0.   ],
       ...,
       [10.   ],
       [ 0.   ],
       [69.116]])

In [54]:
sgd = SGDClassifier()
model = sgd.fit(X_train, y_train_1)
y_pred = model.predict(X_test)

/Users/amith/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


ValueError: Unknown label type: (array([0.0000e+00, 1.2200e-01, 1.4600e-01, ..., 2.2534e+04, 2.6067e+04,
       4.6271e+04]),)

In [55]:
y_train_2 = list(y_train_1)
y_train_2

[array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array

In [65]:
y_train_3 = y_train["sales"]

In [67]:
sgd = SGDClassifier()
model = sgd.fit(X_train, y_train_3)
y_pred = model.predict(X_test)

ValueError: Unknown label type: (array([0.0000e+00, 1.2200e-01, 1.4600e-01, ..., 2.2534e+04, 2.6067e+04,
       4.6271e+04]),)

In [73]:
X_train.head()

date_year  date_month  date_day  store_nbr_0  store_nbr_1  store_nbr_2  \
0       2013           1         1            0            0            0   
1       2013           1         1            0            0            0   
2       2013           1         1            0            0            0   
3       2013           1         1            0            0            0   
4       2013           1         1            0            0            0   

   store_nbr_3  store_nbr_4  store_nbr_5  family_0  ...  type_0  type_1  \
0            0            0            0         0  ...       0       1   
1            0            0            0         0  ...       0       1   
2            0            0            0         0  ...       0       1   
3            0            0            0         0  ...       0       1   
4            0            0            0         0  ...       0       1   

   type_2  cluster_0  cluster_1  cluster_2  cluster_3  cluster_4  dcoilwtico  \
0       1          0          1          1          0          0      93.366   
1       1          0          1          1          0          0      93.366   
2       1          0          1          1          0          0      93.366   
3       1          0          1          1          0          0      93.366   
4       1          0          1          1          0          0      93.366   

   holiday?  
0       1.0  
1       1.0  
2       1.0  
3       1.0  
4       1.0  

[5 rows x 35 columns]

In [74]:
X_train["dcoilwtico"] = X_train["dcoilwtico"].round(2)
X_test["dcoilwtico"] = X_test["dcoilwtico"].round(2)
X_train["holiday?"] = X_train["holiday?"].astype("int64")
X_test["holiday?"] = X_test["holiday?"].astype("int64")
y_train = y_train["sales"]
y_train = y_train.astype("int64")

In [75]:
X_train.head()

date_year  date_month  date_day  store_nbr_0  store_nbr_1  store_nbr_2  \
0       2013           1         1            0            0            0   
1       2013           1         1            0            0            0   
2       2013           1         1            0            0            0   
3       2013           1         1            0            0            0   
4       2013           1         1            0            0            0   

   store_nbr_3  store_nbr_4  store_nbr_5  family_0  ...  type_0  type_1  \
0            0            0            0         0  ...       0       1   
1            0            0            0         0  ...       0       1   
2            0            0            0         0  ...       0       1   
3            0            0            0         0  ...       0       1   
4            0            0            0         0  ...       0       1   

   type_2  cluster_0  cluster_1  cluster_2  cluster_3  cluster_4  dcoilwtico  \
0       1          0          1          1          0          0       93.37   
1       1          0          1          1          0          0       93.37   
2       1          0          1          1          0          0       93.37   
3       1          0          1          1          0          0       93.37   
4       1          0          1          1          0          0       93.37   

   holiday?  
0         1  
1         1  
2         1  
3         1  
4         1  

[5 rows x 35 columns]

In [76]:
X_test.head()

date_year  date_month  date_day  store_nbr_0  store_nbr_1  store_nbr_2  \
0       2017           8        16            0            0            0   
1       2017           8        16            0            0            0   
2       2017           8        16            0            0            0   
3       2017           8        16            0            0            0   
4       2017           8        16            0            0            0   

   store_nbr_3  store_nbr_4  store_nbr_5  family_0  ...  type_0  type_1  \
0            0            0            0         0  ...       0       1   
1            0            0            0         0  ...       0       1   
2            0            0            0         0  ...       0       1   
3            0            0            0         0  ...       0       1   
4            0            0            0         0  ...       0       1   

   type_2  cluster_0  cluster_1  cluster_2  cluster_3  cluster_4  dcoilwtico  \
0       1          0          1          1          0          0        46.8   
1       1          0          1          1          0          0        46.8   
2       1          0          1          1          0          0        46.8   
3       1          0          1          1          0          0        46.8   
4       1          0          1          1          0          0        46.8   

   holiday?  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 35 columns]

In [77]:
y_train.head()

0    0
1    0
2    0
3    0
4    0
Name: sales, dtype: int64