## Machine Learning

Now, we are done with both exploratory data analysis and preprocessing. Now we will go ahead with performing machine learning.

### Importing all packages

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import *
from sklearn.linear_model import *
from math import *
from sklearn.ensemble import *
from sklearn.feature_selection import *
from sklearn.feature_extraction import *
from sklearn.naive_bayes import *
from sklearn.discriminant_analysis import *
from sklearn.preprocessing import *
from sklearn.metrics import *
from sklearn.neighbors import *
from sklearn.cluster import *
from sklearn.kernel_approximation import *
from sklearn.svm import *

In [2]:
df_X = pd.read_csv("train_X_preprocessed.csv")
df_y = pd.read_csv("train_y_preprocessed.csv")
df_test = pd.read_csv("test_preprocessed.csv")

In [3]:
df_X.head()

date_year  date_month  date_day  store_nbr_0  store_nbr_1  store_nbr_2  \
0       2013           1         1            0            0            0   
1       2013           1         1            0            0            0   
2       2013           1         1            0            0            0   
3       2013           1         1            0            0            0   
4       2013           1         1            0            0            0   

   store_nbr_3  store_nbr_4  store_nbr_5  family_0  ...  type_0  type_1  \
0            0            0            0         0  ...       0       1   
1            0            0            0         0  ...       0       1   
2            0            0            0         0  ...       0       1   
3            0            0            0         0  ...       0       1   
4            0            0            0         0  ...       0       1   

   type_2  cluster_0  cluster_1  cluster_2  cluster_3  cluster_4  dcoilwtico  \
0       1          0          1          1          0          0      93.366   
1       1          0          1          1          0          0      93.366   
2       1          0          1          1          0          0      93.366   
3       1          0          1          1          0          0      93.366   
4       1          0          1          1          0          0      93.366   

   holiday?  
0       1.0  
1       1.0  
2       1.0  
3       1.0  
4       1.0  

[5 rows x 35 columns]

In [4]:
df_y.head()

sales
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0

In [5]:
df_test.head()

date_year  date_month  date_day  store_nbr_0  store_nbr_1  store_nbr_2  \
0       2017           8        16            0            0            0   
1       2017           8        16            0            0            0   
2       2017           8        16            0            0            0   
3       2017           8        16            0            0            0   
4       2017           8        16            0            0            0   

   store_nbr_3  store_nbr_4  store_nbr_5  family_0  ...  type_0  type_1  \
0            0            0            0         0  ...       0       1   
1            0            0            0         0  ...       0       1   
2            0            0            0         0  ...       0       1   
3            0            0            0         0  ...       0       1   
4            0            0            0         0  ...       0       1   

   type_2  cluster_0  cluster_1  cluster_2  cluster_3  cluster_4  dcoilwtico  \
0       1          0          1          1          0          0        46.8   
1       1          0          1          1          0          0        46.8   
2       1          0          1          1          0          0        46.8   
3       1          0          1          1          0          0        46.8   
4       1          0          1          1          0          0        46.8   

   holiday?  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  

[5 rows x 35 columns]

In [6]:
print("Number of rows in X_train : ",len(df_X))
print("Number of rows in y_train : ",len(df_y))
print("Number of rows in X_test  : ",len(df_test))

Number of rows in X_train :  1048575
Number of rows in y_train :  1048575
Number of rows in X_test  :  28512


In [7]:
df_X.dtypes

date_year        int64
date_month       int64
date_day         int64
store_nbr_0      int64
store_nbr_1      int64
store_nbr_2      int64
store_nbr_3      int64
store_nbr_4      int64
store_nbr_5      int64
family_0         int64
family_1         int64
family_2         int64
family_3         int64
family_4         int64
family_5         int64
onpromotion      int64
city_0           int64
city_1           int64
city_2           int64
city_3           int64
city_4           int64
state_0          int64
state_1          int64
state_2          int64
state_3          int64
type_0           int64
type_1           int64
type_2           int64
cluster_0        int64
cluster_1        int64
cluster_2        int64
cluster_3        int64
cluster_4        int64
dcoilwtico     float64
holiday?       float64
dtype: object

In [8]:
df_test.dtypes

date_year        int64
date_month       int64
date_day         int64
store_nbr_0      int64
store_nbr_1      int64
store_nbr_2      int64
store_nbr_3      int64
store_nbr_4      int64
store_nbr_5      int64
family_0         int64
family_1         int64
family_2         int64
family_3         int64
family_4         int64
family_5         int64
onpromotion      int64
city_0           int64
city_1           int64
city_2           int64
city_3           int64
city_4           int64
state_0          int64
state_1          int64
state_2          int64
state_3          int64
type_0           int64
type_1           int64
type_2           int64
cluster_0        int64
cluster_1        int64
cluster_2        int64
cluster_3        int64
cluster_4        int64
dcoilwtico     float64
holiday?       float64
dtype: object

In [9]:
df_y.dtypes

sales    float64
dtype: object

### Performing feature engineering in both training and testing datasets

In [10]:
ss = StandardScaler()
df_X_1 = ss.fit_transform(df_X)
df_test_1 = ss.fit_transform(df_test)
df_y_1 = df_y["sales"].astype("int64")

df_X_1 = pd.DataFrame(df_X_1,columns=df_X.columns.values)
df_test_1 = pd.DataFrame(df_test_1,columns=df_test.columns.values)

In [11]:
df_X_1.head()

date_year  date_month  date_day  store_nbr_0  store_nbr_1  store_nbr_2  \
0   -0.78521   -1.446885 -1.646582     -0.82865    -0.829352    -0.894529   
1   -0.78521   -1.446885 -1.646582     -0.82865    -0.829352    -0.894529   
2   -0.78521   -1.446885 -1.646582     -0.82865    -0.829352    -0.894529   
3   -0.78521   -1.446885 -1.646582     -0.82865    -0.829352    -0.894529   
4   -0.78521   -1.446885 -1.646582     -0.82865    -0.829352    -0.894529   

   store_nbr_3  store_nbr_4  store_nbr_5  family_0  ...    type_0    type_1  \
0    -0.963498     -0.96362    -0.999969 -0.176777  ... -0.282862  0.797569   
1    -0.963498     -0.96362    -0.999969 -0.176777  ... -0.282862  0.797569   
2    -0.963498     -0.96362    -0.999969 -0.176777  ... -0.282862  0.797569   
3    -0.963498     -0.96362    -0.999969 -0.176777  ... -0.282862  0.797569   
4    -0.963498     -0.96362    -0.999969 -0.176777  ... -0.282862  0.797569   

     type_2  cluster_0  cluster_1  cluster_2  cluster_3  cluster_4  \
0  1.037688   -0.13731   1.037623   1.037558  -0.928497  -0.963498   
1  1.037688   -0.13731   1.037623   1.037558  -0.928497  -0.963498   
2  1.037688   -0.13731   1.037623   1.037558  -0.928497  -0.963498   
3  1.037688   -0.13731   1.037623   1.037558  -0.928497  -0.963498   
4  1.037688   -0.13731   1.037623   1.037558  -0.928497  -0.963498   

   dcoilwtico  holiday?  
0   -1.350853  2.577187  
1   -1.350853  2.577187  
2   -1.350853  2.577187  
3   -1.350853  2.577187  
4   -1.350853  2.577187  

[5 rows x 35 columns]

In [12]:
df_test_1.head()

date_year  date_month  date_day  store_nbr_0  store_nbr_1  store_nbr_2  \
0        0.0         0.0 -1.626978    -0.829156    -0.829156    -0.894427   
1        0.0         0.0 -1.626978    -0.829156    -0.829156    -0.894427   
2        0.0         0.0 -1.626978    -0.829156    -0.829156    -0.894427   
3        0.0         0.0 -1.626978    -0.829156    -0.829156    -0.894427   
4        0.0         0.0 -1.626978    -0.829156    -0.829156    -0.894427   

   store_nbr_3  store_nbr_4  store_nbr_5  family_0  ...    type_0    type_1  \
0    -0.963624    -0.963624         -1.0 -0.176777  ... -0.282843  0.797724   
1    -0.963624    -0.963624         -1.0 -0.176777  ... -0.282843  0.797724   
2    -0.963624    -0.963624         -1.0 -0.176777  ... -0.282843  0.797724   
3    -0.963624    -0.963624         -1.0 -0.176777  ... -0.282843  0.797724   
4    -0.963624    -0.963624         -1.0 -0.176777  ... -0.282843  0.797724   

     type_2  cluster_0  cluster_1  cluster_2  cluster_3  cluster_4  \
0  1.037749  -0.137361   1.037749   1.037749  -0.928477  -0.963624   
1  1.037749  -0.137361   1.037749   1.037749  -0.928477  -0.963624   
2  1.037749  -0.137361   1.037749   1.037749  -0.928477  -0.963624   
3  1.037749  -0.137361   1.037749   1.037749  -0.928477  -0.963624   
4  1.037749  -0.137361   1.037749   1.037749  -0.928477  -0.963624   

   dcoilwtico  holiday?  
0   -0.679021 -0.258199  
1   -0.679021 -0.258199  
2   -0.679021 -0.258199  
3   -0.679021 -0.258199  
4   -0.679021 -0.258199  

[5 rows x 35 columns]

In [13]:
df_y_1.head()

0    0
1    0
2    0
3    0
4    0
Name: sales, dtype: int64

In [14]:
print("Number of rows in scaled X_train : ",len(df_X_1))
print("Number of rows in scaled y_train : ",len(df_y_1))
print("Number of rows in scaled X_test  : ",len(df_test_1))

Number of rows in scaled X_train :  1048575
Number of rows in scaled y_train :  1048575
Number of rows in scaled X_test  :  28512


In [15]:
X_train = df_X_1.copy()
y_train = df_y_1.copy()
X_test = df_test_1.copy()

In [16]:
sgd = SGDClassifier()
model = sgd.fit(X_train,y_train)
y_test = model.predict(X_test)

KeyboardInterrupt: 

SGDClassifier is taking a lot of time. Let us consider kernel approximation.

In [16]:
rbf = RBFSampler()
X_train_mod = rbf.fit_transform(X_train)
X_test_mod = rbf.fit_transform(X_test)

In [17]:
sgd = SGDClassifier(max_iter=5)
model = sgd.fit(X_train_mod,y_train)
y_test = model.predict(X_test)

KeyboardInterrupt: 

Sci-kit learn is taking a lot of time to perform machine learning. Hence, let us go for deep learning using tensorflow.

### Saving the datasets as tensors

In [18]:
X_train_np = df_X.to_numpy()
y_train_np = df_y.to_numpy()
X_test_np = df_test.to_numpy()

In [21]:
X_train_np[0:5,:]

array([[2.0130e+03, 1.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 1.0000e+00, 1.0000e+00, 0.0000e+00, 1.0000e+00,
        1.0000e+00, 0.0000e+00, 0.0000e+00, 9.3366e+01, 1.0000e+00],
       [2.0130e+03, 1.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 1.0000e+00, 1.0000e+00, 0.0000e+00, 1.0000e+00,
        1.0000e+00, 0.0000e+00, 0.0000e+00, 9.3366e+01, 1.0000e+00],
       [2.0130e+03, 1.0000e+00, 1.0000e+00, 0.

In [22]:
y_train_np[0:5,:]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [23]:
X_test_np[0:5,:]

array([[2.017e+03, 8.000e+00, 1.600e+01, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 1.000e+00,
        1.000e+00, 0.000e+00, 0.000e+00, 4.680e+01, 0.000e+00],
       [2.017e+03, 8.000e+00, 1.600e+01, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 1.000e+00,
        1.000e+00, 0.000e+00, 0.000e+00, 4.680e+01, 0.000e+00],
       [2.017e+03, 8.000e+00, 1.600e+01, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e

In [28]:
print("Number of rows in tensor X_train : ",X_train_np.shape[0])
print("Number of rows in tensor y_train : ",y_train_np.shape[0])
print("Number of rows in tensor X_test  : ",X_test_np.shape[0])

Number of rows in tensor X_train :  1048575
Number of rows in tensor y_train :  1048575
Number of rows in tensor X_test  :  28512
