## Data Preprocessing

Now, we are done with exploratory data analysis of both training and testing datasets. Now, we should get into preprocessing for both the datasets as some of the features are not numerical.

### Importing all packages

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import *
from sklearn.linear_model import *
from math import *
from sklearn.ensemble import *
from sklearn.feature_selection import *
from sklearn.feature_extraction import *
from sklearn.naive_bayes import *
from sklearn.discriminant_analysis import *
from sklearn.preprocessing import *
from sklearn.metrics import *
from sklearn.neighbors import *
from sklearn.cluster import *

### Importing training and testing datasets

In [2]:
df_train = pd.read_csv("train_eda.csv")
df_test = pd.read_csv("test_eda.csv")

In [3]:
df_train.head()

id        date  store_nbr      family  onpromotion   city      state type  \
0   0  2013-01-01          1  AUTOMOTIVE            0  Quito  Pichincha    D   
1   1  2013-01-01          1   BABY CARE            0  Quito  Pichincha    D   
2   2  2013-01-01          1      BEAUTY            0  Quito  Pichincha    D   
3   3  2013-01-01          1   BEVERAGES            0  Quito  Pichincha    D   
4   4  2013-01-01          1       BOOKS            0  Quito  Pichincha    D   

   cluster  dcoilwtico  holiday?  sales  
0       13      93.366       1.0    0.0  
1       13      93.366       1.0    0.0  
2       13      93.366       1.0    0.0  
3       13      93.366       1.0    0.0  
4       13      93.366       1.0    0.0

In [4]:
df_test.head()

id        date  store_nbr      family  onpromotion   city      state  \
0  3000888  2017-08-16          1  AUTOMOTIVE            0  Quito  Pichincha   
1  3000889  2017-08-16          1   BABY CARE            0  Quito  Pichincha   
2  3000890  2017-08-16          1      BEAUTY            2  Quito  Pichincha   
3  3000891  2017-08-16          1   BEVERAGES           20  Quito  Pichincha   
4  3000892  2017-08-16          1       BOOKS            0  Quito  Pichincha   

  type  cluster  dcoilwtico  holiday?  
0    D       13        46.8       0.0  
1    D       13        46.8       0.0  
2    D       13        46.8       0.0  
3    D       13        46.8       0.0  
4    D       13        46.8       0.0

In [5]:
print("Length of training dataset : ",len(df_train))
print("Length of training dataset : ",len(df_test))

Length of training dataset :  1048575
Length of training dataset :  28512


### Description on both training and testing datasets

In [22]:
df_train.describe().round(2)

id   store_nbr  onpromotion     cluster  dcoilwtico  \
count  1048575.00  1048575.00   1048575.00  1048575.00  1048575.00   
mean    524287.00       27.49         0.11        8.48       99.19   
std     302697.67       15.58         2.38        4.65        4.31   
min          0.00        1.00         0.00        1.00       86.65   
25%     262143.50       14.00         0.00        4.00       96.29   
50%     524287.00       27.00         0.00        9.00       99.19   
75%     786430.50       41.00         0.00       13.00      101.92   
max    1048574.00       54.00       196.00       17.00      110.62   

         holiday?       sales  
count  1048575.00  1048575.00  
mean         0.13      244.53  
std          0.34      806.59  
min          0.00        0.00  
25%          0.00        0.00  
50%          0.00        1.00  
75%          0.00      120.00  
max          1.00    46271.00

In [23]:
df_test.describe().round(2)

id  store_nbr  onpromotion   cluster  dcoilwtico  holiday?
count    28512.00   28512.00     28512.00  28512.00    28512.00  28512.00
mean   3015143.50      27.50         6.97      8.48       47.24      0.06
std       8230.85      15.59        20.68      4.65        0.65      0.24
min    3000888.00       1.00         0.00      1.00       45.96      0.00
25%    3008015.75      14.00         0.00      4.00       47.00      0.00
50%    3015143.50      27.50         0.00      8.50       47.24      0.00
75%    3022271.25      41.00         6.00     13.00       47.46      0.00
max    3029399.00      54.00       646.00     17.00       48.59      1.00

### Information about both training and testing datasets

In [24]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 12 columns):
 #   Column       Non-Null Count    Dtype  
---  ------       --------------    -----  
 0   id           1048575 non-null  int64  
 1   date         1048575 non-null  object 
 2   store_nbr    1048575 non-null  int64  
 3   family       1048575 non-null  object 
 4   onpromotion  1048575 non-null  int64  
 5   city         1048575 non-null  object 
 6   state        1048575 non-null  object 
 7   type         1048575 non-null  object 
 8   cluster      1048575 non-null  int64  
 9   dcoilwtico   1048575 non-null  float64
 10  holiday?     1048575 non-null  float64
 11  sales        1048575 non-null  float64
dtypes: float64(3), int64(4), object(5)
memory usage: 96.0+ MB


In [25]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28512 entries, 0 to 28511
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   id           28512 non-null  int64  
 1   date         28512 non-null  object 
 2   store_nbr    28512 non-null  int64  
 3   family       28512 non-null  object 
 4   onpromotion  28512 non-null  int64  
 5   city         28512 non-null  object 
 6   state        28512 non-null  object 
 7   type         28512 non-null  object 
 8   cluster      28512 non-null  int64  
 9   dcoilwtico   28512 non-null  float64
 10  holiday?     28512 non-null  float64
dtypes: float64(2), int64(4), object(5)
memory usage: 2.4+ MB


### Conversion of date from object type to datetime[64ns] type

In [26]:
df_train["date"] = pd.to_datetime(df_train["date"])
df_test["date"] = pd.to_datetime(df_test["date"])

### Store numbers

In [34]:
num_stores_train = (df_train["store_nbr"].unique())
num_stores_train.sort()
num_stores_train

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54])

In [35]:
num_stores_test = (df_test["store_nbr"].unique())
num_stores_test.sort()
num_stores_test

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54])

### Checking for family feature

In [39]:
df_train["family"].unique()

array(['AUTOMOTIVE', 'BABY CARE', 'BEAUTY', 'BEVERAGES', 'BOOKS',
       'BREAD/BAKERY', 'CELEBRATION', 'CLEANING', 'DAIRY', 'DELI', 'EGGS',
       'FROZEN FOODS', 'GROCERY I', 'GROCERY II', 'HARDWARE',
       'HOME AND KITCHEN I', 'HOME AND KITCHEN II', 'HOME APPLIANCES',
       'HOME CARE', 'LADIESWEAR', 'LAWN AND GARDEN', 'LINGERIE',
       'LIQUOR,WINE,BEER', 'MAGAZINES', 'MEATS', 'PERSONAL CARE',
       'PET SUPPLIES', 'PLAYERS AND ELECTRONICS', 'POULTRY',
       'PREPARED FOODS', 'PRODUCE', 'SCHOOL AND OFFICE SUPPLIES',
       'SEAFOOD'], dtype=object)

In [40]:
df_test["family"].unique()

array(['AUTOMOTIVE', 'BABY CARE', 'BEAUTY', 'BEVERAGES', 'BOOKS',
       'BREAD/BAKERY', 'CELEBRATION', 'CLEANING', 'DAIRY', 'DELI', 'EGGS',
       'FROZEN FOODS', 'GROCERY I', 'GROCERY II', 'HARDWARE',
       'HOME AND KITCHEN I', 'HOME AND KITCHEN II', 'HOME APPLIANCES',
       'HOME CARE', 'LADIESWEAR', 'LAWN AND GARDEN', 'LINGERIE',
       'LIQUOR,WINE,BEER', 'MAGAZINES', 'MEATS', 'PERSONAL CARE',
       'PET SUPPLIES', 'PLAYERS AND ELECTRONICS', 'POULTRY',
       'PREPARED FOODS', 'PRODUCE', 'SCHOOL AND OFFICE SUPPLIES',
       'SEAFOOD'], dtype=object)

### Performing ordinal encoding the family feature

In [57]:
oe = OrdinalEncoder()
num1 = oe.fit_transform(df_train["family"].values.reshape(-1,1))
num2 = oe.fit_transform(df_test["family"].values.reshape(-1,1))

In [58]:
num1

array([[ 0.],
       [ 1.],
       [ 2.],
       ...,
       [30.],
       [31.],
       [32.]])

In [59]:
num2

array([[ 0.],
       [ 1.],
       [ 2.],
       ...,
       [30.],
       [31.],
       [32.]])

In [60]:
df_train_1 = df_train.copy()
df_test_1 = df_test.copy()

In [61]:
df_train_1["family"] = num1
df_test_1["family"] = num2

In [62]:
df_train_1.head()

id       date  store_nbr  family  onpromotion   city      state type  \
0   0 2013-01-01          1     0.0            0  Quito  Pichincha    D   
1   1 2013-01-01          1     1.0            0  Quito  Pichincha    D   
2   2 2013-01-01          1     2.0            0  Quito  Pichincha    D   
3   3 2013-01-01          1     3.0            0  Quito  Pichincha    D   
4   4 2013-01-01          1     4.0            0  Quito  Pichincha    D   

   cluster  dcoilwtico  holiday?  sales  
0       13      93.366       1.0    0.0  
1       13      93.366       1.0    0.0  
2       13      93.366       1.0    0.0  
3       13      93.366       1.0    0.0  
4       13      93.366       1.0    0.0

In [63]:
df_test_1.head()

id       date  store_nbr  family  onpromotion   city      state type  \
0  3000888 2017-08-16          1     0.0            0  Quito  Pichincha    D   
1  3000889 2017-08-16          1     1.0            0  Quito  Pichincha    D   
2  3000890 2017-08-16          1     2.0            2  Quito  Pichincha    D   
3  3000891 2017-08-16          1     3.0           20  Quito  Pichincha    D   
4  3000892 2017-08-16          1     4.0            0  Quito  Pichincha    D   

   cluster  dcoilwtico  holiday?  
0       13        46.8       0.0  
1       13        46.8       0.0  
2       13        46.8       0.0  
3       13        46.8       0.0  
4       13        46.8       0.0

In [64]:
print("Length of training dataset : ",len(df_train_1))
print("Length of training dataset : ",len(df_test_1))

Length of training dataset :  1048575
Length of training dataset :  28512


In [68]:
print("Unique numbers for training data family : ",list(df_train_1["family"].unique()))

Unique numbers for training data family :  [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0]


In [69]:
print("Unique numbers for testing data family  : ",list(df_test_1["family"].unique()))

Unique numbers for testing data family  :  [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0]


### Checking for on-promotion feature

In [70]:
df_train_1["onpromotion"].unique()

array([  0,   3,   5,   1,  56,  20,  19,   2,   4,  18,  17,  12,   6,
         7,  10,   9,  50,   8,  16,  42,  51,  13,  15,  47,  21,  40,
        37,  54,  24,  58,  22,  59,  11,  45,  25,  55,  26,  43,  35,
        14,  28,  46,  36,  32,  53,  57,  27,  39,  41,  30,  29,  49,
        23,  48,  44,  38,  31,  52,  33,  34,  61,  60, 116,  86,  73,
       113, 102,  68, 104,  93,  70,  92, 121,  72, 178, 174, 161, 118,
       105, 172, 163, 167, 142, 154, 133, 180, 181, 173, 165, 168, 186,
       140, 149, 145, 169, 188,  62,  84, 111,  65, 107,  63, 101,  87,
       125,  94, 114, 171, 153, 170, 166, 141, 155, 179, 192, 131, 147,
       151, 189,  79,  74, 110,  64,  67,  99, 123, 157, 117, 150, 182,
       162, 160, 194, 135, 190,  69, 108,  89, 126, 156, 103, 146, 132,
       177, 164, 176, 112,  75, 109,  91, 128, 175, 187, 148, 137, 184,
       196, 144, 158])

In [71]:
df_test_1["onpromotion"].unique()

array([  0,   2,  20,  12,  25,  45,  18,   1,  64,   6,  10,  16,   5,
         9, 256,  14,  43,  15,  30, 106,  96,  19, 230,  52,  35, 145,
       102,   4,   3,   8, 163,  38,  17,  29, 115,  87, 219,  33, 107,
        90, 244,  31, 114,  88, 223,  32, 105, 208,  34, 108,  97, 211,
       139,  91, 177,  40, 161,  21, 156,  39,  28, 116,  89, 220,  23,
        22,  41,  65,  11, 255, 150,  92, 178,  13,  46, 148,  98, 170,
        37, 122, 203,  24,  70, 253,  63, 254,  44,  42, 252,  47, 151,
       101, 175,  36, 152, 104, 168,  60, 110,  93, 205, 141, 172,  94,
       225, 126,  95, 197, 138, 212, 142,  99, 173,  26,  57,  51, 155,
        61, 129, 182,  62, 146, 159,  56,  59, 154, 158,   7,  53,  27,
        68,  66,  69,  49,  50,  48,  55,  54,  58,  74,  72,  78,  77,
        73,  84,  76,  80,  67,  79, 133,  86, 144, 125, 137, 140, 160,
       119, 127, 128,  83,  81,  82, 118, 124, 180, 210, 131, 228, 112,
       135, 186, 202, 237, 224, 218, 171, 206, 191, 229,  71,  8

### Checking for city feature

In [72]:
df_train_1["city"].unique()

array(['Quito', 'Cayambe', 'Latacunga', 'Riobamba', 'Ibarra',
       'Santo Domingo', 'Guaranda', 'Puyo', 'Ambato', 'Guayaquil',
       'Salinas', 'Daule', 'Babahoyo', 'Quevedo', 'Playas', 'Libertad',
       'Cuenca', 'Loja', 'Machala', 'Esmeraldas', 'Manta', 'El Carmen'],
      dtype=object)

In [73]:
df_test_1["city"].unique()

array(['Quito', 'Cayambe', 'Latacunga', 'Riobamba', 'Ibarra',
       'Santo Domingo', 'Guaranda', 'Puyo', 'Ambato', 'Guayaquil',
       'Salinas', 'Daule', 'Babahoyo', 'Quevedo', 'Playas', 'Libertad',
       'Cuenca', 'Loja', 'Machala', 'Esmeraldas', 'Manta', 'El Carmen'],
      dtype=object)

In [75]:
(df_train_1["city"].unique() == df_test_1["city"].unique()).sum()

22

### Performing ordinal encoding on the city column

In [77]:
oe1 = OrdinalEncoder()
train_pe1 = oe1.fit_transform(df_train_1["city"].values.reshape(-1,1))
test_pe1 = oe1.fit_transform(df_test_1["city"].values.reshape(-1,1))

In [79]:
df_train_2 = df_train_1.copy()
df_test_2 = df_test_1.copy()

In [80]:
df_train_2["city"] = train_pe1
df_test_2["city"] = test_pe1

In [81]:
df_train_2.head()

id       date  store_nbr  family  onpromotion  city      state type  \
0   0 2013-01-01          1     0.0            0  18.0  Pichincha    D   
1   1 2013-01-01          1     1.0            0  18.0  Pichincha    D   
2   2 2013-01-01          1     2.0            0  18.0  Pichincha    D   
3   3 2013-01-01          1     3.0            0  18.0  Pichincha    D   
4   4 2013-01-01          1     4.0            0  18.0  Pichincha    D   

   cluster  dcoilwtico  holiday?  sales  
0       13      93.366       1.0    0.0  
1       13      93.366       1.0    0.0  
2       13      93.366       1.0    0.0  
3       13      93.366       1.0    0.0  
4       13      93.366       1.0    0.0

In [82]:
df_test_2.head()

id       date  store_nbr  family  onpromotion  city      state type  \
0  3000888 2017-08-16          1     0.0            0  18.0  Pichincha    D   
1  3000889 2017-08-16          1     1.0            0  18.0  Pichincha    D   
2  3000890 2017-08-16          1     2.0            2  18.0  Pichincha    D   
3  3000891 2017-08-16          1     3.0           20  18.0  Pichincha    D   
4  3000892 2017-08-16          1     4.0            0  18.0  Pichincha    D   

   cluster  dcoilwtico  holiday?  
0       13        46.8       0.0  
1       13        46.8       0.0  
2       13        46.8       0.0  
3       13        46.8       0.0  
4       13        46.8       0.0

In [83]:
print("Length of training dataset : ",len(df_train_2))
print("Length of training dataset : ",len(df_test_2))

Length of training dataset :  1048575
Length of training dataset :  28512
